### ISSUE TITLE
Nullpointer in checkMaskedappsFormat

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#412]
One potential explanation of this null pointer is non-firefox browser did not set the parameter correctly. Hence, either,  `LocalRunKeyMap` or `runkeyName` is `null`. 
It's not clear how to reproduce this bug, we should put some debug messages in the code.

https://github.com/HCALRunControl/levelOneHCALFM/blob/18.1.4/src/rcms/fm/app/level1/HCALlevelOneEventHandler.java#L1669
```
 2018-04-14 12:51:07 and 332 ms : cms.hcalpro.rcms.fm.fw.user.UserEventHandler
     ERROR EventHandler: callback method initAction failure
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at rcms.fm.fw.user.UserEventHandler.invokeActions(UserEventHandler.java:237)
at rcms.fm.fw.user.UserEventHandler.handleEvent(UserEventHandler.java:220)
at rcms.fm.fw.EventHandlerManager.handleEvent(EventHandlerManager.java:131)
at rcms.fm.fw.EventProcessor.processEvent(EventProcessor.java:100)
at rcms.fm.fw.FunctionManager.processEvent(FunctionManager.java:1253)
at rcms.fm.fw.FunctionManager.access$500(FunctionManager.java:51)
at rcms.fm.fw.FunctionManager$ConsumerThread.run(FunctionManager.java:1200)
Caused by: java.lang.NullPointerException
at rcms.fm.app.level1.HCALlevelOneEventHandler.checkMaskedappsFormat(HCALlevelOneEventHandler.java:1669)
at rcms.fm.app.level1.HCALlevelOneEventHandler.initAction(HCALlevelOneEventHandler.java:335)
... 11 more
```

**Comment by kakwok** [comment]
Have not seen same issue again.
